name: Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: sync

jobs:
  export:
    name: "Export"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: ./run.sh
        env:
          CLOUDFLARE_TOKEN: ${{ secret.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secret.CLOUDFLARE_ZONE_ID }}
          WIKI_BOT_USERNAME: ${{ secret.WIKI_BOT_USERNAME }}
          WIKI_BOT_PASSWORD: ${{ secret.WIKI_BOT_PASSWORD }}